version: "3.8"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: expenses
    volumes:
      - db-data:/var/lib/mysql
      - ./db-migration/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"

volumes:
  db-data:
